
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 15:16:36 CST 2018
//----------------------------------------------------

package php.scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bolCnst = 11;
  public static final int include = 51;
  public static final int t_for = 23;
  public static final int curly_C = 43;
  public static final int curly_A = 42;
  public static final int brackets = 13;
  public static final int plus = 46;
  public static final int t_null = 37;
  public static final int mod = 49;
  public static final int t_void = 14;
  public static final int minus = 2;
  public static final int t_return = 25;
  public static final int t_interface = 20;
  public static final int neg = 31;
  public static final int t_else = 22;
  public static final int t_implements = 19;
  public static final int extend = 44;
  public static final int comma = 17;
  public static final int malloc = 32;
  public static final int cmpop = 3;
  public static final int t_if = 21;
  public static final int intCnst = 53;
  public static final int t_new = 45;
  public static final int t_newArr = 38;
  public static final int clase = 18;
  public static final int ReadLine = 34;
  public static final int divide = 48;
  public static final int EOF = 0;
  public static final int readInteger = 33;
  public static final int ident = 5;
  public static final int pyc = 6;
  public static final int prnthss_C = 16;
  public static final int prnthss_A = 15;
  public static final int error = 1;
  public static final int equals = 41;
  public static final int times = 47;
  public static final int dblConst = 36;
  public static final int t_string = 10;
  public static final int logop = 4;
  public static final int library = 52;
  public static final int getByte = 39;
  public static final int setByte = 40;
  public static final int t_break = 26;
  public static final int strConst = 12;
  public static final int print = 27;
  public static final int t_bool = 9;
  public static final int constante = 50;
  public static final int t_double = 8;
  public static final int brackets_C = 30;
  public static final int t_this = 28;
  public static final int brackets_A = 29;
  public static final int dot = 35;
  public static final int t_int = 7;
  public static final int t_while = 24;
}

