
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 06 21:30:36 CST 2018
//----------------------------------------------------

package php.scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bolCnst = 10;
  public static final int t_for = 22;
  public static final int curly_C = 44;
  public static final int curly_A = 43;
  public static final int brackets = 12;
  public static final int t_null = 38;
  public static final int t_void = 13;
  public static final int t_return = 24;
  public static final int arop = 2;
  public static final int t_interface = 19;
  public static final int neg = 31;
  public static final int t_else = 21;
  public static final int t_implements = 18;
  public static final int extend = 45;
  public static final int comma = 16;
  public static final int malloc = 32;
  public static final int t_if = 20;
  public static final int intCnst = 37;
  public static final int t_new = 46;
  public static final int t_newArr = 39;
  public static final int clase = 17;
  public static final int ReadLine = 34;
  public static final int EOF = 0;
  public static final int readInteger = 33;
  public static final int ident = 4;
  public static final int pyc = 5;
  public static final int prnthss_C = 15;
  public static final int prnthss_A = 14;
  public static final int error = 1;
  public static final int equals = 42;
  public static final int dblConst = 36;
  public static final int t_string = 9;
  public static final int logop = 3;
  public static final int getByte = 40;
  public static final int setByte = 41;
  public static final int t_break = 25;
  public static final int prnthss = 28;
  public static final int strConst = 11;
  public static final int print = 26;
  public static final int t_bool = 8;
  public static final int t_double = 7;
  public static final int brackets_C = 30;
  public static final int t_this = 27;
  public static final int brackets_A = 29;
  public static final int dot = 35;
  public static final int t_int = 6;
  public static final int t_while = 23;
}

