package php.scanner;
public enum Token { 
    T_IDENTIFIER, EQUALS, PLUS, TIMES, ASSIGN, MINUS, ERROR,  
    AROP, CMPOP, LOGOP, ASSOP, INCDECOP, PRNTHSS, CURLY,  
    BRACKET, SEMICOLON, COMMA, BOOL, INT, DOUBLE, T_STRINGCONSTANT,  
    VARID, CONSTANT, CTRLSTRCT, RSRVDVAR, COMMENT, DB, FUNC,  
    NEWLINE, BLANK, MAGCONSTANT, T_RSRVWRDS, PHP, CONCAT , T_INTCONSTANT,
    T_BOOLCONSTANT, T_DOUBLECONSTANT, T_PUNCTUATION, T_BINOP, T_UNOP
     
} 